# SPlugin Config

# in features you can enable/disable various features from this plugin.
features:
  skipNight: true # Enable skipping the night when a certain percentage of players sleep.
  afk: true # Enable AFK displaying when players are inactive for 2 minutes
  showGroup: true # Enable the showing of the group a user belongs to in chat. Example: "Default | player: Hi!"

skipNight:
  percentage: 50

# If you provide a token, the bot will accept commands for the server.
# If you provide at least one guild and channel combination, the server will stream all
# discord activity to the server and vice versa.
discord:
  token: null # Your discord bot token
  channels:
    # GUILD_ID: CHANNEL_ID
    # You can have 1 channel per guild.
    # You can define multiple combinations to stream to multiple channels in multiple guilds.
  joinMessage: false # Whether or not to send a message to discord when a player joins the server.
  leaveMessage: false # Whether or not to send a message to discord when a player leaves the server.

messages:
  join:
    - "[player] has joined the server!"
  leave:
    - "[player] has left the server!"
  death:
    - "[message]..."
  welcome:
    - "Welcome [player]!"
  welcomeBack:
    - "Welcome back, [player]!"
  skipNight:
    - "Skipping the night..."
  nightSkipped:
    - "The night has been skipped!"
  everyoneSleeping:
    - "Everyone is sleeping!"
  sleeping:
    - "[sleeping] are currently sleeping. [needed] to skip the night."