# BlockProt Config

inventories:
  back: "Back"
  block_info: # Info inventory for server admins
    name: "Block Info"
  add_friend:
    name: "Add Friend"
    items:
      search: "Search"
  remove_friend:
    name: "Remove Friend"
  friend_search:
    name: "Search Players"
  friend_search_result:
    name: "Players found"
  block_lock: # The inventory with all buttons
    name: "Block Lock"
    items:
      add_friends: "Add Friends"
      remove_friends: "Remove Friends"
      info: "Info"
      lock:
        lock: "Lock"
        unlock: "Unlock"
      redstone:
        activate: "Activate Redstone"
        deactivate: "Deactivate Redstone"
  user_settings:
    name: "User Settings"
    items:
      lock_on_place:
        activate: "Always lock on placing"
        deactivate: "Never lock on placing"
      add_friends: "Add Friends"
      remove_friends: "Remove Friends"

messages:
  permission_granted: # When a user locks a block
    text: "Permission granted."
  unlocked: # When a block gets unlocked
    text: "Unlocked."
  no_permission:
    text: "No permission."
  friend_added:
    text: "Friend added."
  friend_removed:
    text: "Friend removed."
  friend_already_added:
    text: "Friend already added."
  friend_cant_be_removed:
    text: "Friend cannot be removed."
  redstone_added:
    text: "Redstone protection added."
  redstone_removed:
    text: "Redstone protection removed."
