# BlockProt Config

# Load a language file from the plugins/BlockProt/ directory.
# You can create your own language files and edit existing ones.
# If the language file could not be found, we default to "translations_en.yml".
language_file: translations_en.yml

# If set to "true", anytime an admin joins the server, they will
# receive an in-game message if this plugin is outdated.
# If set to "false", no message will be sent but /blockprot update
# will still work.
notify_op_of_updates: false

# If set to "true", redstone will be automatically disallowed on every
# placed block, if the player has lock on place enabled.
redstone_disallowed_by_default: false
