main: de.sean.splugin.SPlugin
name: SPlugin
version: 0.1
api-version: 1.13
dependencies:
  - NBTAPI
permissions:
  splugin.lock:
    description: Allows a player to lock a chest/hopper ...

  splugin.sit:
    description: Allows a player to sit on stairs ...
