name: BlockProt CI

on:
  # push:
  #   branches: [ master ]
  #   paths:
  #     - 'BlockProt/src/**'
  #     - '**.gradle'
  #   ignore-paths:
  #     - 'SPlugin/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'BlockProt/src/**'
      - '**.gradle'
    ignore-paths:
      - 'SPlugin/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: BlockProt
        