name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'gradle/**'
      - '**.gradle'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: BlockProt CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check for errors
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: .*src/.*.kt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        run: ./gradlew build
