name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'gradle/**'
      - '**.gradle'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Check for errors
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: .*src/.*.kt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
