name: Release

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - run: ./gradlew build curseforge github --stacktrace
        env:
          GIT_TAG: ${{ steps.vars.outputs.tag }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
